version: '3.8'

services:
  ts-auth-service:
    build: .
    container_name: ts-auth-service-1625
    ports:
      - "1625:1625"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
